### ISSUE TITLE
"TypeError: process.hrtime is not a function"

### ISSUE THREAD

**Issue by thearabbit** [onury/perfy#3]
I base on `Meteor + Vue`
```js
// Vue
import perfy from 'perfy'
.....
submitForm() {
          perfy.start('report')
          this.loading = true

          reportAccountList
            .callPromise(this.form)
            .then(result => {
              this.reportData = result

              this.execution = perfy.end('report').time
              this.loading = false
            })
            .catch(error => {
              this.loading = false
            })
    },
```

**Comment by thearabbit** [comment]
I tried in server code 
```js
TypeError: perfy.start is not a function
```

**Comment by onury** [comment]
I don't know how you transpile your code but `perfy` is a ES5 package (uses `module.export`). So it's important how you bundle your project if you're using `import`.

See [this test using babel](https://github.com/onury/perfy/files/2576225/perfy-test.zip). This runs the following command to transpile:
`npx babel index.js --out-file index-compiled.js --sourceType module --presets=@babel/preset-env`

And below works as expected:
```js
import perfy from 'perfy';            // works
// import * as perfy from 'perfy';    // also works
// const perfy = require('perfy');    // also works

perfy.start('test1');
setTimeout(() => {
    const result = perfy.end('test1');
    console.log(result);
}, 1000);
```

**Comment by onury** [comment]
By the way, title of this issue is `TypeError: process.hrtime is not a function`. 
Are you trying to use `perfy` in a browser environment? If so you can't. perfy is a lib for Node.js. It uses `process` object which is only available in Node.js (i.e. server side).

**Comment by thearabbit** [comment]
Thanks for your reply.
Now work fine on `Server Side`
